---
title: "T-test"
author: "Magda G."
date: "9 sierpnia 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## T-Test

This is data from the French validation of the Affective Style Questionnaire.

```{r}
# Load packages
library(tidyverse)

# devtools::install_github("neuropsychology/psycho.R")  # Install the latest psycho version
library(psycho)

df <- psycho::affective  # Load the data
results <- t.test(df$Age ~ df$Sex)  # Perform a simple t-test

results
psycho::analyze(results)
```

It works for all kinds of different t-tests versions.


```{r}
t.test(df$Adjusting ~ df$Sex,
       var.equal=TRUE, 
       conf.level = .90) %>% 
  psycho::analyze()
```

```{r}
t.test(df$Adjusting,
       mu=0,
       conf.level = .90) %>% 
  psycho::analyze()
```

It is also possible to have all the values stored in a dataframe by running a summary on the analyzed object.

```{r}
t.test(df$Adjusting ~ df$Sex) %>% 
  psycho::analyze() %>% 
  summary()
```

```{r}
t.test(df$Age ~ df$Sex) %>% 
  psycho::analyze() %>% 
  summary()
```

